#
# Module manifest for module 'PureStoragePowerShellSDK'
#
# Generated by: Pure Storage, Inc.
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'PureStoragePowerShellSDK2.dll'

    # Version number of this module.
    ModuleVersion = '2.2.267.0'

    # ID used to uniquely identify this module
    GUID = 'a12b790d-4a25-46c3-a457-910bc7203e1f'

    # Author of this module
    Author = 'Pure Storage, Inc.'

    # Company or vendor of this module
    CompanyName = 'Pure Storage, Inc.'

    # Copyright statement for this module
    Copyright = '(c) 2020 Pure Storage, Inc. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Pure Storage FlashArray REST 2.x API integration with Windows PowerShell.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    DotNetFrameworkVersion = '3.5'

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'None'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = 'Newtonsoft.Json.dll', 'PureStorage.Rest.Shared.Std.dll'

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = '*'

    # Cmdlets to export from this module
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = '*'

    # List of all modules packaged with this module
    ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        #support for PowerShellGet galleries.
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('PureStorage')
            
            # A URL to the license for this module.
            LicenseUri = ''
            
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/PureStorage-Connect/PowerShellSDK'
            
            # A URL to an icon representing this module.
            IconUri = ''
            
            # ReleaseNotes of this module
            ReleaseNotes = ''
        }        
    }

    # HelpInfo URI of this module
    HelpInfoURI = 'http://connect.pure1.purestorage.com/powershell/PureStoragePowerShellSDK2/2.2'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}

